/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/game-specs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Game Specs */
        get: operations["list_game_specs_game_specs_get"];
        put?: never;
        /** Create Game Spec */
        post: operations["create_game_spec_game_specs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/game-specs/{game_spec_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Game Spec */
        get: operations["get_game_spec_game_specs__game_spec_id__get"];
        /** Update Game Spec */
        put: operations["update_game_spec_game_specs__game_spec_id__put"];
        post?: never;
        /** Delete Game Spec */
        delete: operations["delete_game_spec_game_specs__game_spec_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** GameSpec */
        GameSpec: {
            /** Title */
            title: string;
            /** Brand */
            brand?: string | null;
            /**
             * Release Date
             * Format: date
             */
            release_date: string;
            /** Id */
            id?: string;
        };
        /** GameSpecCreate */
        GameSpecCreate: {
            /** Title */
            title: string;
            /** Brand */
            brand?: string | null;
            /**
             * Release Date
             * Format: date
             */
            release_date: string;
        };
        /** GameSpecListResponse */
        GameSpecListResponse: {
            /** Items */
            items: components["schemas"]["GameSpec"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** GameSpecUpdate */
        GameSpecUpdate: {
            /** Title */
            title: string;
            /** Brand */
            brand?: string | null;
            /**
             * Release Date
             * Format: date
             */
            release_date: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_game_specs_game_specs_get: {
        parameters: {
            query?: {
                title?: string | null;
                brand?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: {
                "x-console-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameSpecListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_game_spec_game_specs_post: {
        parameters: {
            query?: never;
            header?: {
                "x-console-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GameSpecCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameSpec"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_game_spec_game_specs__game_spec_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-console-token"?: string | null;
            };
            path: {
                game_spec_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameSpec"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_game_spec_game_specs__game_spec_id__put: {
        parameters: {
            query?: never;
            header?: {
                "x-console-token"?: string | null;
            };
            path: {
                game_spec_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GameSpecUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameSpec"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_game_spec_game_specs__game_spec_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-console-token"?: string | null;
            };
            path: {
                game_spec_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
